# Generated by Django 6.1.1 on 2026-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Зарезервированный никнейм')),
            ],
            options={
                'verbose_name': 'Зарезервированный никнейм',
                'verbose_name_plural': 'Зарезервированные никнеймы',
            },
        ),
    ]
