# Generated by Django 6.1.1 on 2026-10-02 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reservedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_telegram_verified',
            field=models.BooleanField(default=False, verbose_name='Telegram подтвержден'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Telegram Username'),
        ),
        migrations.CreateModel(
            name='TelegramVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tg_code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
