# Generated by Django 6.1.1 on 2026-10-02 08:37

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramverificationcode',
            name='created_at',
        ),
        migrations.AddField(
            model_name='telegramverificationcode',
            name='expires_at',
            field=models.DateTimeField(default=users.models.one_hour_hence),
        ),
    ]
