services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - volleykarelia_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s


  app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    environment:
      # Внутри compose PostgreSQL доступен как db.
      DATABASE_URL: ${DOCKER_DATABASE_URL}

      HOST: 0.0.0.0
      PORT: 8000

    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=3)"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

    # App доступен только локально на VDS.
    # Внешний HTTP/HTTPS принимает системный Nginx.
    ports:
      - "127.0.0.1:8000:8000"

    command:
      ["python3", "-m", "src.entrypoint"]


volumes:
  volleykarelia_postgres_data:

