# Generated by Django 6.1.1 on 2026-09-30 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='Ссылка на команду')),
                ('name', models.CharField(max_length=255, verbose_name='Название команды')),
                ('league', models.CharField(blank=True, max_length=255, null=True, verbose_name='Лига/Дивизион')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('users', models.ManyToManyField(blank=True, related_name='tracked_teams', to=settings.AUTH_USER_MODEL, verbose_name='Отслеживающие пользователи')),
            ],
            options={
                'verbose_name': 'Отслеживаемая команда',
                'verbose_name_plural': 'Отслеживаемые команды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящая'), ('completed', 'Завершённая')], default='upcoming', max_length=20, verbose_name='Статус игры')),
                ('matchup_text', models.CharField(max_length=255, verbose_name='Матч / Вывеска')),
                ('date_str', models.CharField(max_length=100, verbose_name='Дата и время')),
                ('score', models.CharField(blank=True, max_length=50, null=True, verbose_name='Счет')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='schedule.trackedteam', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['id'],
            },
        ),
    ]
