# Generated by Django 6.1.1 on 2026-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата игры'),
        ),
    ]
