# Generated by Django 6.1.1 on 2026-09-29 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0002_teamplayer_team_players'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Причина пропуска')),
                ('is_default', models.BooleanField(default=False, verbose_name='Системная причина')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reasons', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Причина пропуска',
                'verbose_name_plural': 'Причины пропусков',
                'ordering': ['-is_default', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутствовал')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='players.player', verbose_name='Игрок')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.absencereason', verbose_name='Причина пропуска')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.training', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'unique_together': {('training', 'player')},
            },
        ),
    ]
